version: '3'

services:

  flask:
    container_name: flask
    build:
      context: application
      dockerfile: Dockerfile    
    restart: unless-stopped
    environment:
      BUILD: ${BUILD}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_PORT: ${APP_PORT}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - primary

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: unless-stopped  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx-local:/etc/nginx/conf.d
    depends_on: 
      - flask
    networks:
      - primary


networks:
  primary:
      driver: bridge
      

volumes:
    app-data:
      driver: local
    nginx-data:
      driver: local  